pool:
  name: Default
variables:
  BuildConfiguration: 'Release'

steps:
- script: 'dotnet-sdk.dotnet build **/Apex.Collections.csproj -c $(BuildConfiguration)'
  displayName: 'dotnet preview build'

- script: |
   dotnet-sdk.dotnet test **/*.Tests.csproj -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  /p:Include="[Apex.*]*"
   
   echo "##vso[task.prependpath]$HOME/.dotnet/tools"
  displayName: 'dotnet preview test'

- script: 'dotnet tool install -g dotnet-reportgenerator-globaltool'
  displayName: 'Install report generator tool'
  enabled: false

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/coverage.cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
    failIfCoverageEmpty: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/Apex.Collections.csproj'
    nobuild: true
    versioningScheme: byPrereleaseNumber
    verbosityPack: Minimal

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    publishVstsFeed: '07ec90d7-e26d-4498-b734-0d6335b66f3c'

